#!/usr/bin/env python3
"""
cxe2hex.py — Convert a .cxe binary into a flat Verilog $readmemh hex image.

Usage:
    python3 cxe2hex.py <input.cxe> <output.hex> [--flash-size BYTES]

The output is a flat byte-addressed hex image sized to --flash-size (default
65536 = 64 KB, matching RAM_WORDS=16384 × 4 bytes).

Each line of the .hex file is one byte in two hex digits, e.g.:
    43
    58
    45
    ...

The CXE header stays at offset 0. Each section's data is placed at its vaddr.
Unfilled bytes are 00.

The flash loader FSM in cxis_cpu.v does a verbatim memcpy of flash→RAM, then
reads entry_point from bytes [8..11] of the image to set PC.

Example:
    python3 cxe2hex.py tests/hello.cxe hello.hex
    iverilog -o sim cxis_cpu_flash_tb.v cxis_cpu.v
    vvp sim
"""

import struct
import sys
import os

CXE_MAGIC   = 0x45585843   # "CXXE" little-endian  (matches cxe.h CXE_MAGIC)
HEADER_SIZE = 20            # sizeof(CxeHeader) with pack(push,1)
SECTION_SIZE = 20           # sizeof(CxeSection)

def parse_cxe(data: bytes) -> tuple[int, list[tuple[int,int,bytes]]]:
    """
    Returns (entry_point, [(vaddr, mem_size, section_bytes), ...]).
    Raises ValueError on bad magic/version.
    """
    if len(data) < HEADER_SIZE:
        raise ValueError("File too small to be a valid .cxe")

    magic, version, flags, entry_point, section_count = \
        struct.unpack_from('<IHHIH', data, 0)
    # reserved[6] follows — skip

    if magic != CXE_MAGIC:
        raise ValueError(f"Bad magic: 0x{magic:08X} (expected 0x{CXE_MAGIC:08X})")

    sections = []
    sec_off = HEADER_SIZE  # offset of first section header in file

    for i in range(section_count):
        if sec_off + SECTION_SIZE > len(data):
            raise ValueError(f"Truncated section header {i}")
        vaddr, file_offset, file_size, mem_size, sec_flags = \
            struct.unpack_from('<IIIIBB', data, sec_off)[:5]
        # unpack full struct: vaddr(4) offset(4) file_size(4) mem_size(4) flags(1) reserved(3)
        vaddr, file_offset, file_size, mem_size, sec_flags, *_ = \
            struct.unpack_from('<IIIIBxxx', data, sec_off)

        CXE_SEC_ZERO = 0x08
        if sec_flags & CXE_SEC_ZERO:
            sec_data = bytes(mem_size)          # BSS: zero-fill
        else:
            sec_data = data[file_offset : file_offset + file_size]
            if len(sec_data) < file_size:
                raise ValueError(f"Section {i} data truncated")
            # Pad to mem_size with zeros
            sec_data = sec_data + bytes(mem_size - file_size)

        sections.append((vaddr, mem_size, sec_data))
        sec_off += SECTION_SIZE

    return entry_point, sections


def cxe_to_hex(cxe_path: str, hex_path: str, flash_size: int = 65536):
    with open(cxe_path, 'rb') as f:
        data = f.read()

    entry_point, sections = parse_cxe(data)

    # Flat image, all zeros
    image = bytearray(flash_size)

    # Copy CXE header + section headers verbatim at offset 0
    hdr_len = HEADER_SIZE + len(sections) * SECTION_SIZE
    if hdr_len > flash_size:
        raise ValueError("Flash too small for CXE headers")
    image[0:len(data[:hdr_len])] = data[:hdr_len]

    # Place each section at its vaddr
    for vaddr, mem_size, sec_data in sections:
        end = vaddr + len(sec_data)
        if end > flash_size:
            raise ValueError(
                f"Section at vaddr=0x{vaddr:08X} size={len(sec_data)} "
                f"overflows flash ({flash_size} bytes)"
            )
        image[vaddr : vaddr + len(sec_data)] = sec_data

    # Write hex file: one byte per line, two hex digits
    with open(hex_path, 'w') as f:
        f.write(f"// Generated by cxe2hex.py from {os.path.basename(cxe_path)}\n")
        f.write(f"// entry_point = 0x{entry_point:08X}\n")
        f.write(f"// flash_size  = {flash_size} bytes\n")
        for byte in image:
            f.write(f"{byte:02x}\n")

    print(f"[cxe2hex] {cxe_path} → {hex_path}")
    print(f"          entry_point = 0x{entry_point:08X}")
    print(f"          flash_size  = {flash_size} bytes")
    for i, (vaddr, mem_size, _) in enumerate(sections):
        print(f"          section[{i}]  vaddr=0x{vaddr:08X}  size={mem_size}")


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(description='Convert .cxe to Verilog $readmemh hex image')
    ap.add_argument('input',  help='Input .cxe file')
    ap.add_argument('output', help='Output .hex file')
    ap.add_argument('--flash-size', type=int, default=65536,
                    help='Flash image size in bytes (default: 65536 = 64KB)')
    args = ap.parse_args()

    try:
        cxe_to_hex(args.input, args.output, args.flash_size)
    except (ValueError, FileNotFoundError) as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
